const LOAD_TICKET_CALLS_REQUEST = "tickets:LOAD_TICKET_CALLS_REQUEST";
const LOAD_TICKET_CALLS_SUCCESS = "tickets:LOAD_TICKET_CALLS_SUCCESS";
const LOAD_TICKET_CALLS_FAILURE = "tickets:LOAD_TICKET_CALLS_FAILURE";

const CREATE_TICKET_CALL_REQUEST = "tickets:CREATE_TICKET_CALL_REQUEST";
const CREATE_TICKET_CALL_SUCCESS = "tickets:CREATE_TICKET_CALL_SUCCESS";
const CREATE_TICKET_CALL_FAILURE = "tickets:CREATE_TICKET_CALL_FAILURE";

const LOAD_TICKET_CATEGORIES_REQUEST = "tickets:LOAD_TICKET_CATEGORIES_REQUEST";
const LOAD_TICKET_CATEGORIES_SUCCESS = "tickets:LOAD_TICKET_CATEGORIES_SUCCESS";
const LOAD_TICKET_CATEGORIES_FAILURE = "tickets:LOAD_TICKET_CATEGORIES_FAILURE";

export default {
  LOAD_TICKET_CALLS_REQUEST,
  LOAD_TICKET_CALLS_SUCCESS,
  LOAD_TICKET_CALLS_FAILURE,
  CREATE_TICKET_CALL_REQUEST,
  CREATE_TICKET_CALL_SUCCESS,
  CREATE_TICKET_CALL_FAILURE,
  LOAD_TICKET_CATEGORIES_REQUEST,
  LOAD_TICKET_CATEGORIES_SUCCESS,
  LOAD_TICKET_CATEGORIES_FAILURE,
};
