const LOAD_PRODUCERS_REQUEST = "tickets:LOAD_PRODUCERS_REQUEST";
const LOAD_PRODUCERS_SUCCESS = "tickets:LOAD_PRODUCERS_SUCCESS";
const LOAD_PRODUCERS_FAILURE = "tickets:LOAD_PRODUCERS_FAILURE";

const LOAD_PRODUCER_DETAILS_REQUEST = "tickets:LOAD_PRODUCER_DETAILS_REQUEST";
const LOAD_PRODUCER_DETAILS_SUCCESS = "tickets:LOAD_PRODUCER_DETAILS_SUCCESS";
const LOAD_PRODUCER_DETAILS_FAILURE = "tickets:LOAD_PRODUCER_DETAILS_FAILURE";

const CREATE_PRODUCER_REQUEST = "tickets:CREATE_PRODUCER_REQUEST";
const CREATE_PRODUCER_SUCCESS = "tickets:CREATE_PRODUCER_SUCCESS";
const CREATE_PRODUCER_FAILURE = "tickets:CREATE_PRODUCER_FAILURE";

const UPDATE_PRODUCER_REQUEST = "tickets:UPDATE_PRODUCER_REQUEST";
const UPDATE_PRODUCER_SUCCESS = "tickets:UPDATE_PRODUCER_SUCCESS";
const UPDATE_PRODUCER_FAILURE = "tickets:UPDATE_PRODUCER_FAILURE";

const DELETE_PRODUCER_REQUEST = "tickets:DELETE_PRODUCER_REQUEST";
const DELETE_PRODUCER_SUCCESS = "tickets:DELETE_PRODUCER_SUCCESS";
const DELETE_PRODUCER_FAILURE = "tickets:DELETE_PRODUCER_FAILURE";

export default {
  LOAD_PRODUCERS_REQUEST,
  LOAD_PRODUCERS_SUCCESS,
  LOAD_PRODUCERS_FAILURE,
  LOAD_PRODUCER_DETAILS_REQUEST,
  LOAD_PRODUCER_DETAILS_SUCCESS,
  LOAD_PRODUCER_DETAILS_FAILURE,
  CREATE_PRODUCER_REQUEST,
  CREATE_PRODUCER_SUCCESS,
  CREATE_PRODUCER_FAILURE,
  UPDATE_PRODUCER_REQUEST,
  UPDATE_PRODUCER_SUCCESS,
  UPDATE_PRODUCER_FAILURE,
  DELETE_PRODUCER_REQUEST,
  DELETE_PRODUCER_SUCCESS,
  DELETE_PRODUCER_FAILURE,
};
