const CREATE_FARM_REQUEST = "farms:CREATE_FARM_REQUEST";
const CREATE_FARM_SUCCESS = "farms:CREATE_FARM_SUCCESS";
const CREATE_FARM_FAILURE = "farms:CREATE_FARM_FAILURE";

export default {
  CREATE_FARM_REQUEST,
  CREATE_FARM_SUCCESS,
  CREATE_FARM_FAILURE,
};
